# Generated by Django 5.0.7 on 2024-10-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
