# Generated by Django 5.0.7 on 2024-10-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('picture', models.ImageField(upload_to='candidate_pictures/')),
                ('manifesto', models.TextField()),
                ('motto', models.CharField(max_length=100)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_app.election')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.seat')),
            ],
        ),
    ]
