# Generated by Django 5.0.7 on 2024-09-02 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(upload_to='candidate_pictures/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.seat'),
        ),
    ]
