# Generated by Django 5.0.7 on 2024-07-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('seat', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Candidiate',
        ),
    ]
