# Generated by Django 5.0.7 on 2024-07-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_delete_candidiate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
