# Generated by Django 5.0.7 on 2024-08-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Election',
            new_name='Elections',
        ),
    ]
